# Generated by Django 4.1.10 on 2023-11-06 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footballmatches",
            old_name="awa_team",
            new_name="away_team",
        ),
    ]
