# Generated by Django 4.1.10 on 2023-11-06 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FootballMatches",
        ),
    ]
