# Generated by Django 4.1.10 on 2023-11-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_sci", "0009_delete_footballmatches"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootballMatches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_team", models.CharField(max_length=255)),
                ("away_team", models.CharField(max_length=255)),
                ("home_goals", models.IntegerField()),
                ("away_goals", models.IntegerField()),
                ("date", models.DateField()),
                ("result", models.CharField(max_length=1)),
            ],
        ),
    ]
