# Generated by Django 4.1.10 on 2023-11-15 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0010_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FootballMatches",
        ),
    ]
